F1. Al Fine (Maximizing Version)
time limit per test3 seconds
memory limit per test512 megabytes

This is the maximizing version of the problem. The difference between the versions is that in this version, you need to find the maximum possible depth among all common trees. Also, the constraint on n
 in this version is larger. You can hack only if you solved all versions of this problem.

For Christmas, Tortinita and Arietta each get a Christmas tree. Coincidentally, their trees share the same properties: both have n+1
 vertices and are rooted at vertex 0
. In their Christmas card to you, each of them appends a DFS order sequence of their tree after their greetings. Recall that a DFS order sequence is generated by the following pseudocode.

dfs_order = []

def dfs(v):
    dfs_order.append(v)
    pick an arbitrary permutation s of children of v
    for child in s:
        dfs(child)

dfs(root)
Let the DFS order sequence of Tortinita's tree be a0,a1,…,an
 and that of Arietta's tree be b0,b1,…,bn
. You observe that a0=b0=0
, and since they are twin sisters, you wonder if they could have the exact same tree. You also feel that for their Christmas tree, the sisters would not choose a trivial structure. Therefore, you want to find the maximum possible depth∗
 among all common trees for both sequences.

∗
The depth of a tree is defined as the maximum number of edges on a simple path from any node to the root.

Input
Each test contains multiple test cases. The first line contains the number of test cases t
 (1≤t≤104
). The description of the test cases follows.

The first line of each test case contains one integer n
 (2≤n≤106
).

The second line of each test case contains n
 integers a1,a2,⋯,an
 (1≤ai≤n
).

The third line of each test case contains n
 integers b1,b2,⋯,bn
 (1≤bi≤n
).

It is guaranteed that neither sequence a
 nor b
 contains duplicates.

It is guaranteed that the sum of n
 over all test cases does not exceed 106
.

Output
For each test case, output one integer — the maximum possible depth among all common trees.

Example
InputCopy
4
2
1 2
1 2
2
1 2
2 1
5
3 1 5 2 4
4 3 2 1 5
5
2 3 4 1 5
3 2 1 4 5
OutputCopy
2
1
3
1
Note
In the first test case, a
 and b
 are the same. Consider a link tree with edges (0,1)
 and (1,2)
; it can give either DFS order sequence, and its depth is 2
. It can be shown that 2
 is the maximum depth among all possible common trees.

In the second test case, consider a star-shaped tree with edges (0,1)
 and (0,2)
, whose depth is 1
. It can be shown that 1
 is the maximum depth among all possible common trees.

In the third test case, the figure shows one of the trees with the maximum depth of 3
.#include <bits/stdc++.h>
using i64 = long long;

void solve() {
    int n;
    std::cin >> n;
    std::vector<int> a(n+1), b(n+1);
    for (int i = 1; i <= n; ++i) std::cin >> a[i];
    for (int i = 1; i <= n; ++i) std::cin >> b[i];
    std::vector<int> mp(n+1), c(n+1), R(n+1);
    for (int i = 1; i <= n; ++i) mp[b[i]] = i;
    for (int i = 1; i <= n; ++i) c[i] = mp[a[i]];
    for (int i = 1; i <= n; ++i) mp[c[i]] = i;
    std::vector<int> min(n + 1), max(n + 1);
    std::vector<std::vector<std::pair<int, int>>> rmax(2 * n + 1);
    std::vector<int> p(2 * n + 1);

    auto work = [&](auto &&self, int l, int r) -> void {
        if (l >= r) return;
        int mid = l + (r - l) / 2;
        self(self, l, mid);
        self(self, mid + 1, r);
        min[mid] = max[mid] = c[mid];
        for (int i = mid - 1; i >= l; --i) {
            min[i] = std::min(min[i + 1], c[i]);
            max[i] = std::max(max[i + 1], c[i]);
        }
        min[mid + 1] = max[mid + 1] = c[mid + 1];
        rmax[c[mid + 1] - mid - 1 + n].emplace_back(c[mid + 1], mid + 1);
        for (int i = mid + 2; i <= r; ++i) {
            min[i] = std::min(min[i - 1], c[i]);
            max[i] = std::max(max[i - 1], c[i]);
            rmax[max[i] - i + n].emplace_back(min[i], i);
        }
        for (int i = mid; i >= l; --i) {
            if (min[i] != min[i + 1]) {
                int j = i + max[i] - min[i];
                if (j > mid && j <= r && min[j] > min[i] && max[j] < max[i]) {
                    R[i] = std::max(R[i], j);
                }
                j = min[i] - i + n;
                while (p[j] < std::ssize(rmax[j]) && rmax[j][p[j]].first > min[i]) {
                    ++p[j];
                }
                if (p[j]) {
                    int k = rmax[j][p[j] - 1].second;
                    if (max[k] > max[i]) R[i] = std::max(R[i], k);
                }
            }
        }
        for (int i = mid + 1; i <= r; ++i) {
            rmax[max[i] - i + n].clear();
            p[max[i] - i + n] = 0;
        }
    };
    work(work, 1, n);

    std::stack<int> st;
    int ans = 0;
    for (int i = 1; i <= n; ++i) {
        while (!st.empty() && st.top() <= i) st.pop();
        if (R[i]) {
            st.push(R[i]);
            ans = std::max(ans, int(st.size()));
        }
    }
    std::cout << (ans + 1) << '\n';
}

int main() {
    std::cin.tie(nullptr)->sync_with_stdio(false);
    int T = 1;
    std::cin >> T;
    while (T--) solve();
    return 0;
}
